drone:  
  model_name: "hummingbird"

sensor:
  lidar_range: 4.
  lidar_vfov: [-10, 20.] # degree 设置LiDAR的垂直视场角(Field of View)
  lidar_vbeams: 4 # number of vertical beams
  lidar_hres: 10. # degree
  